In [199]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib as plt

#Import cranial database 
df = pd.read_csv('../../datasources/fdb/cranial.csv')
#This shuffles the rows.
df = df.sample(frac=1)

#Drop categorical data. We'll focus only on measurement data.
del df['DB']
del df['Item']
del df['ID']
del df['ContNum']
del df['FDN']
del df['Pop']
del df['PopSex']
del df['Ethnicity'] #Probably really important.
del df['BirthYear']
del df['Age'] #Probably really important.
del df['Comments']

#This col is basically empty and disturbs standardization.
del df["MOW"]

rows, cols = df.shape 
print("Starting with", rows, "individuals and", cols, "features.")

Starting with 5342 individuals and 110 features.

In [200]:
#Consider our target col, Sex.
print("Unique entries.")
df['Sex'].value_counts(dropna=False)

Unique entries.

M      3187
F      2095
N        58
NaN       2
Name: Sex, dtype: int64

In [201]:
#Clean N and Nan entries
df = df[~(df.Sex.str.contains("N") == True)]
df = df.dropna(subset = ['Sex'])

#Move from object to float.
df['Sex'] = df['Sex'].map({'M':1.0, 'F':0.})
df.describe()

,Sex,GOL,NOL,BNL,BBH,XCB,XFB,WFB,ZYB,AUB,...,MLN,MAN,BABR,BANA,BAPR,UFHT,UFBR,ORBR,BIOB,INTB
count,5282.000000,5200.000000,4396.000000,5177.000000,5182.000000,5196.000000,4395.000000,2622.000000,5096.000000,5106.000000,...,519.000000,518.000000,636.000000,607.000000,574.000000,2115.000000,1605.000000,453.000000,604.000000,413.000000
mean,0.603370,180.397500,177.689945,100.143906,133.846584,137.568129,114.752673,94.898932,129.449372,120.855660,...,77.046243,124.990347,136.886792,101.494234,97.031359,70.201891,103.535826,41.008830,96.253311,20.552058
std,0.489244,8.838111,8.238570,5.764435,7.336864,6.811824,6.477442,4.952665,7.313785,6.763771,...,7.211489,7.455211,6.889893,5.523686,6.481473,4.934519,4.827782,2.493338,4.400408,3.388348
min,0.000000,131.000000,150.000000,79.000000,107.000000,116.000000,93.000000,79.000000,90.000000,98.000000,...,54.000000,90.000000,84.000000,85.000000,73.000000,47.000000,87.000000,34.000000,81.000000,0.000000
25%,0.000000,174.000000,172.000000,96.000000,129.000000,133.000000,110.000000,92.000000,124.000000,116.000000,...,73.000000,120.250000,133.000000,98.000000,93.000000,67.000000,100.000000,39.000000,93.000000,19.000000
50%,1.000000,180.000000,178.000000,100.000000,134.000000,137.000000,115.000000,95.000000,129.000000,121.000000,...,77.000000,125.000000,137.000000,101.000000,97.000000,70.000000,104.000000,41.000000,96.000000,21.000000
75%,1.000000,187.000000,183.000000,104.000000,139.000000,142.000000,119.000000,98.000000,134.000000,125.000000,...,81.000000,130.000000,142.000000,105.000000,101.000000,74.000000,107.000000,42.000000,99.000000,22.000000
max,1.000000,211.000000,207.000000,120.000000,157.000000,167.000000,145.000000,119.000000,158.000000,154.000000,...,120.000000,147.000000,156.000000,130.000000,116.000000,91.000000,122.000000,51.000000,112.000000,29.000000

In [202]:
#Split into data and labels.
X = df.drop(['Sex'], axis=1)
y = df[['Sex']]

In [203]:
#Split train test
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [204]:
X_train.isnull().sum().sum()

163680

In [205]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((4225, 109), (1057, 109), (4225, 1), (1057, 1))

In [206]:
#Standardize df. Can't use scikit's scale because it doesn't like Nan.
X_train_mean = X_train.mean()
X_train_std = X_train.std()
X_train = (X_train - X_train_mean) / (X_train_std)
#Intentionally using train stats for test set.
X_test = ( X_test - X_train_mean) / (X_train_std)
X_train.describe()

,GOL,NOL,BNL,BBH,XCB,XFB,WFB,ZYB,AUB,ASB,...,MLN,MAN,BABR,BANA,BAPR,UFHT,UFBR,ORBR,BIOB,INTB
count,4.158000e+03,3.490000e+03,4.134000e+03,4.142000e+03,4.158000e+03,3.493000e+03,2.102000e+03,4.068000e+03,4.082000e+03,3.490000e+03,...,4.170000e+02,4.160000e+02,5.140000e+02,4.900000e+02,4.660000e+02,1.708000e+03,1.294000e+03,3.670000e+02,4.870000e+02,3.320000e+02
mean,-1.109689e-15,1.479619e-15,8.855734e-16,1.397884e-15,1.121598e-15,2.797648e-16,1.172336e-15,-2.673214e-16,-8.273637e-16,6.065826e-16,...,-1.332534e-16,-7.104360e-16,-1.566300e-15,-5.102494e-16,3.533178e-16,-2.537328e-16,1.228624e-16,1.398821e-15,1.521028e-15,-2.006427e-16
std,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
min,-5.578697e+00,-3.367987e+00,-3.655352e+00,-3.488171e+00,-3.159272e+00,-3.354610e+00,-3.230522e+00,-5.390989e+00,-3.375820e+00,-3.050422e+00,...,-3.224532e+00,-3.209740e+00,-7.555541e+00,-2.939213e+00,-3.664889e+00,-4.692913e+00,-3.487215e+00,-2.825116e+00,-2.777565e+00,-6.038160e+00
25%,-7.245847e-01,-6.948488e-01,-7.194567e-01,-6.568415e-01,-6.716779e-01,-7.357615e-01,-5.950658e-01,-7.452954e-01,-7.173088e-01,-7.370141e-01,...,-5.841882e-01,-6.406478e-01,-5.553256e-01,-6.269014e-01,-5.926848e-01,-6.436604e-01,-7.620486e-01,-8.142208e-01,-7.451666e-01,-4.720759e-01
50%,-4.726674e-02,3.418887e-02,-2.865796e-02,1.728445e-02,-8.636160e-02,3.448813e-02,1.311652e-02,7.453290e-02,2.116649e-02,-7.604039e-02,...,-2.832630e-02,3.542903e-02,1.612056e-02,-9.329106e-02,2.175595e-02,-3.627258e-02,7.646406e-02,-9.862702e-03,-6.770026e-02,1.138276e-01
75%,7.429376e-01,6.417202e-01,6.621408e-01,6.914104e-01,6.452838e-01,6.506879e-01,6.212988e-01,6.210851e-01,6.119467e-01,5.849333e-01,...,5.275356e-01,7.115058e-01,7.304282e-01,6.181894e-01,6.361967e-01,5.711153e-01,7.053486e-01,3.923163e-01,6.097660e-01,6.997312e-01
max,3.452210e+00,3.557871e+00,3.425336e+00,3.118264e+00,4.303511e+00,3.885736e+00,4.878575e+00,3.900398e+00,4.895103e+00,3.559315e+00,...,5.947189e+00,3.010167e+00,2.444767e+00,5.064942e+00,2.940350e+00,4.215442e+00,3.849771e+00,4.011928e+00,3.545453e+00,2.457442e+00

In [207]:
#The imputer. I haven't looked closely at this algo. Try other variations.
from fancyimpute import KNN
X_train_filled = pd.DataFrame(KNN(k=3).complete(X_train))
X_test_filled = pd.DataFrame(KNN(k=3).complete(X_test))

Computing pairwise distances between 4225 samples
Computing distances for sample #1/4225, elapsed time: 1.981
Computing distances for sample #101/4225, elapsed time: 2.229
No samples have sufficient overlap with sample 139
Computing distances for sample #201/4225, elapsed time: 2.484
Computing distances for sample #301/4225, elapsed time: 2.717
No samples have sufficient overlap with sample 396
Computing distances for sample #401/4225, elapsed time: 2.959
No samples have sufficient overlap with sample 409
No samples have sufficient overlap with sample 421
Computing distances for sample #501/4225, elapsed time: 3.211
Computing distances for sample #601/4225, elapsed time: 3.457
Computing distances for sample #701/4225, elapsed time: 3.695
No samples have sufficient overlap with sample 710
Computing distances for sample #801/4225, elapsed time: 3.929
Computing distances for sample #901/4225, elapsed time: 4.173
No samples have sufficient overlap with sample 904
Computing distances for sample #1001/4225, elapsed time: 4.414
No samples have sufficient overlap with sample 1033
Computing distances for sample #1101/4225, elapsed time: 4.670
Computing distances for sample #1201/4225, elapsed time: 4.907
No samples have sufficient overlap with sample 1269
Computing distances for sample #1301/4225, elapsed time: 5.164
Computing distances for sample #1401/4225, elapsed time: 5.415
Computing distances for sample #1501/4225, elapsed time: 5.656
Computing distances for sample #1601/4225, elapsed time: 5.895
Computing distances for sample #1701/4225, elapsed time: 6.138
Computing distances for sample #1801/4225, elapsed time: 6.377
Computing distances for sample #1901/4225, elapsed time: 6.614
No samples have sufficient overlap with sample 1933
Computing distances for sample #2001/4225, elapsed time: 6.870
No samples have sufficient overlap with sample 2078
Computing distances for sample #2101/4225, elapsed time: 7.122
Computing distances for sample #2201/4225, elapsed time: 7.363
No samples have sufficient overlap with sample 2246
Computing distances for sample #2301/4225, elapsed time: 7.623
No samples have sufficient overlap with sample 2397
Computing distances for sample #2401/4225, elapsed time: 7.857
Computing distances for sample #2501/4225, elapsed time: 8.093
Computing distances for sample #2601/4225, elapsed time: 8.337
No samples have sufficient overlap with sample 2678
Computing distances for sample #2701/4225, elapsed time: 8.592
Computing distances for sample #2801/4225, elapsed time: 8.831
Computing distances for sample #2901/4225, elapsed time: 9.070
Computing distances for sample #3001/4225, elapsed time: 9.301
Computing distances for sample #3101/4225, elapsed time: 9.533
No samples have sufficient overlap with sample 3152
Computing distances for sample #3201/4225, elapsed time: 9.790
Computing distances for sample #3301/4225, elapsed time: 10.027
No samples have sufficient overlap with sample 3351
Computing distances for sample #3401/4225, elapsed time: 10.282
Computing distances for sample #3501/4225, elapsed time: 10.515
Computing distances for sample #3601/4225, elapsed time: 10.755
Computing distances for sample #3701/4225, elapsed time: 10.995
No samples have sufficient overlap with sample 3713
Computing distances for sample #3801/4225, elapsed time: 11.224
No samples have sufficient overlap with sample 3858
Computing distances for sample #3901/4225, elapsed time: 11.480
Computing distances for sample #4001/4225, elapsed time: 11.717
Computing distances for sample #4101/4225, elapsed time: 11.959
Computing distances for sample #4201/4225, elapsed time: 12.223
Imputing row 1/4225 with 39 missing columns, elapsed time: 13.499
Imputing row 101/4225 with 29 missing columns, elapsed time: 13.631
Imputing row 201/4225 with 28 missing columns, elapsed time: 13.747
Imputing row 301/4225 with 18 missing columns, elapsed time: 13.869
Imputing row 401/4225 with 84 missing columns, elapsed time: 14.000
Imputing row 501/4225 with 83 missing columns, elapsed time: 14.110
Imputing row 601/4225 with 28 missing columns, elapsed time: 14.232
Imputing row 701/4225 with 27 missing columns, elapsed time: 14.341
Imputing row 801/4225 with 39 missing columns, elapsed time: 14.455
Imputing row 901/4225 with 18 missing columns, elapsed time: 14.581
Imputing row 1001/4225 with 58 missing columns, elapsed time: 14.713
Imputing row 1101/4225 with 86 missing columns, elapsed time: 14.834
Imputing row 1201/4225 with 25 missing columns, elapsed time: 14.951
Imputing row 1301/4225 with 28 missing columns, elapsed time: 15.068
Imputing row 1401/4225 with 28 missing columns, elapsed time: 15.168
Imputing row 1501/4225 with 28 missing columns, elapsed time: 15.290
Imputing row 1601/4225 with 75 missing columns, elapsed time: 15.411
Imputing row 1701/4225 with 18 missing columns, elapsed time: 15.537
Imputing row 1801/4225 with 58 missing columns, elapsed time: 15.654
Imputing row 1901/4225 with 2 missing columns, elapsed time: 15.765
Imputing row 2001/4225 with 4 missing columns, elapsed time: 15.876
Imputing row 2101/4225 with 25 missing columns, elapsed time: 15.976
Imputing row 2201/4225 with 28 missing columns, elapsed time: 16.102
Imputing row 2301/4225 with 28 missing columns, elapsed time: 16.229
Imputing row 2401/4225 with 28 missing columns, elapsed time: 16.351
Imputing row 2501/4225 with 29 missing columns, elapsed time: 16.465
Imputing row 2601/4225 with 28 missing columns, elapsed time: 16.592
Imputing row 2701/4225 with 25 missing columns, elapsed time: 16.714
Imputing row 2801/4225 with 28 missing columns, elapsed time: 16.820
Imputing row 2901/4225 with 28 missing columns, elapsed time: 16.950
Imputing row 3001/4225 with 101 missing columns, elapsed time: 17.064
Imputing row 3101/4225 with 84 missing columns, elapsed time: 17.175
Imputing row 3201/4225 with 19 missing columns, elapsed time: 17.276
Imputing row 3301/4225 with 39 missing columns, elapsed time: 17.397
Imputing row 3401/4225 with 27 missing columns, elapsed time: 17.515
Imputing row 3501/4225 with 77 missing columns, elapsed time: 17.628
Imputing row 3601/4225 with 58 missing columns, elapsed time: 17.751
Imputing row 3701/4225 with 28 missing columns, elapsed time: 17.867
Imputing row 3801/4225 with 103 missing columns, elapsed time: 17.983
Imputing row 3901/4225 with 18 missing columns, elapsed time: 18.094
Imputing row 4001/4225 with 28 missing columns, elapsed time: 18.221
Imputing row 4101/4225 with 3 missing columns, elapsed time: 18.344
Imputing row 4201/4225 with 39 missing columns, elapsed time: 18.450
[KNN] Warning: 6457/460525 still missing after imputation, replacing with 0
Computing pairwise distances between 1057 samples
Computing distances for sample #1/1057, elapsed time: 0.096
Computing distances for sample #101/1057, elapsed time: 0.149
Computing distances for sample #201/1057, elapsed time: 0.201
Computing distances for sample #301/1057, elapsed time: 0.255
Computing distances for sample #401/1057, elapsed time: 0.305
Computing distances for sample #501/1057, elapsed time: 0.360
Computing distances for sample #601/1057, elapsed time: 0.412
No samples have sufficient overlap with sample 646
Computing distances for sample #701/1057, elapsed time: 0.464
Computing distances for sample #801/1057, elapsed time: 0.516
Computing distances for sample #901/1057, elapsed time: 0.568
Computing distances for sample #1001/1057, elapsed time: 0.621
Imputing row 1/1057 with 28 missing columns, elapsed time: 0.720
Imputing row 101/1057 with 28 missing columns, elapsed time: 0.768
Imputing row 201/1057 with 18 missing columns, elapsed time: 0.824
Imputing row 301/1057 with 28 missing columns, elapsed time: 0.880
Imputing row 401/1057 with 28 missing columns, elapsed time: 0.936
Imputing row 501/1057 with 39 missing columns, elapsed time: 0.991
Imputing row 601/1057 with 28 missing columns, elapsed time: 1.043
Imputing row 701/1057 with 25 missing columns, elapsed time: 1.099
Imputing row 801/1057 with 28 missing columns, elapsed time: 1.151
Imputing row 901/1057 with 39 missing columns, elapsed time: 1.198
Imputing row 1001/1057 with 26 missing columns, elapsed time: 1.248
[KNN] Warning: 588/115213 still missing after imputation, replacing with 0

In [208]:
#Num zero entries
(X_train_filled == 0).astype(int).sum().sum(),(X_test_filled == 0).astype(int).sum().sum()

(6457, 588)

In [209]:
#Impute zeros with mean. Could do this better.
#Think this introduces an improbable bug when the train set
#Has representation in a col that the test set doesn't or 
#Vice versa. Ignoring it for now. 
from sklearn.preprocessing import Imputer
imp = Imputer(missing_values=0, strategy='mean', axis=0)
X_train_filled = pd.DataFrame(imp.fit_transform(X_train_filled))
X_train_filled = pd.DataFrame(imp.transform(X_train_filled))
X_test_filled = pd.DataFrame(imp.fit_transform(X_test_filled))

In [210]:
#No zero values
(X_train_filled == 0).astype(int).sum().sum(), (X_test_filled == 0).astype(int).sum().sum()

(0, 0)

In [211]:
#Notice that the training (and testing) set is no longer standardized
X_train_filled.describe()

,0,1,2,3,4,5,6,7,8,9,...,99,100,101,102,103,104,105,106,107,108
count,4225.000000,4225.000000,4225.000000,4225.000000,4225.000000,4225.000000,4225.000000,4225.000000,4225.000000,4225.000000,...,4225.000000,4225.000000,4225.000000,4225.000000,4225.000000,4225.000000,4225.000000,4225.000000,4225.000000,4225.000000
mean,0.001656,0.032549,0.003616,0.003588,0.001804,0.019404,-0.093083,-0.008431,0.001040,0.028736,...,0.070353,0.227656,-0.268149,-0.059113,0.140030,-0.191663,-0.140561,0.085212,-0.007881,-0.034940
std,0.993224,0.971927,0.992640,0.993499,0.993506,0.950067,0.894621,0.988405,0.990170,0.957859,...,0.534100,0.535358,0.842188,0.823970,0.757669,0.854835,0.736098,0.685014,0.796483,0.613454
min,-5.578697,-3.367987,-3.655352,-3.488171,-3.159272,-3.354610,-3.230522,-5.390989,-3.375820,-3.050422,...,-3.224532,-3.209740,-7.555541,-2.939213,-3.664889,-4.692913,-3.487215,-2.825116,-2.777565,-6.038160
25%,-0.724585,-0.576141,-0.719457,-0.656842,-0.671678,-0.581712,-0.735038,-0.745295,-0.717309,-0.571771,...,-0.213388,0.002472,-0.856247,-0.542380,-0.307880,-0.708440,-0.552420,-0.408506,-0.570710,-0.432821
50%,-0.047267,0.034189,-0.028658,0.017284,-0.086362,0.034488,-0.174989,-0.008431,0.021166,0.044900,...,0.070353,0.234274,-0.285930,-0.135187,0.131579,-0.164918,-0.166376,0.033226,-0.098223,-0.023698
75%,0.742938,0.641720,0.662141,0.691410,0.645284,0.650688,0.457463,0.621085,0.611947,0.639815,...,0.396314,0.541004,0.311427,0.440319,0.613307,0.298536,0.266185,0.530029,0.556258,0.395670
max,3.452210,3.557871,3.425336,3.118264,4.303511,3.885736,4.878575,3.900398,4.895103,3.559315,...,5.947189,3.010167,2.444767,5.064942,2.940350,4.215442,3.849771,4.011928,3.545453,2.457442

In [212]:
#Should we standardize again?
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(X_train_filled)
X_train_filled = pd.DataFrame(scaler.transform(X_train_filled))
#Uses test stats
X_test_filled = pd.DataFrame(scaler.transform(X_test_filled))

In [213]:
#Save to disk
X_train_filled.to_csv("data/X_train_preproc.csv", index=False)
#Ravel strips col name and reindexes
pd.DataFrame(np.ravel(y_train)).to_csv("data/y_train_preproc.csv", index=False)

X_test_filled.to_csv("data/X_test_preproc.csv", index=False)
pd.DataFrame(np.ravel(y_test)).to_csv("data/y_test_preproc.csv", index=False)